### ISSUE TITLE
cloud-database brouw-apparatuur

### ISSUE THREAD

**Issue by 0ridan** [bliekp/BrouwHulp#15]
Er zijn op de Belgische markt twee grote spelers die standaard brouw-apparatuur leveren. Echter is deze brouwapparatuur niet terug te vinden in de brouwhulp software.

**Hoe zou je het graag zien?**
een cloud-database naar het voorbeeld van freedb (tagging van mp3-bestanden) waarin je je ketel kan selecteren. hierdoor hoeft brouwhulp zelf de lijst niet up-to-date te houden, en kan de community de gegevens finetunen.

**Welke alternatieven heb je zelf nog bedacht?**
brouwhulp die zelf deze data up-to-date houdt in het programma.

**Comment by bliekp** [comment]
Je idee is dus vooral dat we een centraal punt hebben waarop we data administreren. Dit verhaal geldt eigenlijk niet alleen voor brouwapparatuur, maar ook voor ingredienten, waterprofielen et cetera.

Je komt ook gelijk met een oplossing. Of dat ook de meest gewenste oplossing is moeten we gaan zien. Vooralsnog valt je vraag denk in twee delen uiteen:

1. voeg nieuwe brouwapparatuur toe.
2. bedenk een oplossing voor het snel syncen van nieuwe brouwapparatuur, ingredienten, etc

Het lijkt me beter om hier twee aparte issues voor te maken. Bij de 1e graag toevoegen welke brouwapparatuur je bedoelt. 

Vooralsnog sluit ik dit request af omdat het niet eenduidig is en verwarring kan scheppen. Bovendien zou je hiermee bereiken dat het wel eens lang kan gaan duren voor je brouwketels zijn toegevoegd omdat we wachten op iemand die jouw cloud-idee oppakt. Dat wil je vast ook niet :).
